GET {{ usersAppUrl }}/actuator/health

###
GET {{ mailerAppUrl }}/actuator/health

###

< {%
    client.global.clearAll();
    client.global.set('name', `John Snow ${$random.integer()}`)
    client.global.set('email', `jsnow+${$random.integer()}@mail.net`)
%}

POST {{ usersAppUrl }}/users
Content-Type: application/json

{
  "name": "{{ name }}",
  "email": "{{ email }}"
}

> {%
    client.test('User created', () => {
        client.assert(!!response.body['id'], 'ID is missed')
        client.assert(response.body['name'] == client.global.get('name'), "Wrong name")
        client.assert(response.body['email'] == client.global.get('email'), "Wrong email")
        client.global.set('userId', response.body['id'])
    })
%}

###

GET {{ usersAppUrl }}/users/{{ userId }}

> {%
    client.test('User loaded', () => {
        client.assert(response.body['id'] == client.global.get('userId'), "Wrong ID")
        client.assert(response.body['name'] == client.global.get('name'), "Wrong name")
        client.assert(response.body['email'] == client.global.get('email'), "Wrong email")
    })
%}

###

< {%
    client.global.set('name', `${client.global.get('name')} updated ${$random.integer()}`)
    client.global.set('email', `updated+${$random.integer()}+${client.global.get('email')}`)
%}
PUT {{ usersAppUrl }}/users/{{ userId }}
Content-Type: application/json

{
  "name": "{{ name }}",
  "email": "{{ email }}"
}

> {%
    client.test('User updated', () => {
        client.assert(response.body['id'] == client.global.get('userId'), "Wrong ID")
        client.assert(response.body['name'] == client.global.get('name'), "Wrong name")
        client.assert(response.body['email'] == client.global.get('email'), "Wrong email")
    })
%}

###

GET {{ usersAppUrl }}/users/{{ userId }}

> {%
    client.test('User loaded', () => {
        client.assert(response.body['id'] == client.global.get('userId'), "Wrong ID")
        client.assert(response.body['name'] == client.global.get('name'), "Wrong name")
        client.assert(response.body['email'] == client.global.get('email'), "Wrong email")
    })
%}
