spring:
  application:
    name: users-app

  datasource:
    url: jdbc:postgresql://localhost:5432/shortcut-users
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30_000
      maximum-pool-size: 50
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      register-mbeans: true
  liquibase:
    change-log: classpath:/migrations/changelog-master.xml
  data:
    web:
      pageable:
        one-indexed-parameters: true

  lifecycle:
    timeout-per-shutdown-phase: 1m

  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  mvc:
    problemdetails:
      enabled: true

server:
  shutdown: graceful

scheduler:
  default-lock:
    lock-at-least-for: PT1M
    lock-at-most-for: PT10M
  message-outbox-handler:
    initial-delay: PT10S
    fixed-delay: PT1S
    lock-at-least-for: ${scheduler.message-outbox-handler.fixed-delay}
    lock-at-most-for: PT5M
  message-outbox-cleaner:
    cron: 0 0 6 * * *
    lock-at-least-for: PT1M
    lock-at-most-for: PT12H
    valid-period: P10D

management:
  endpoints:
    web:
      exposure:
        include: "*"
