spring:
  application:
    name: users-app

  datasource:
    url: jdbc:postgresql://localhost:5432/shortcut-users
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30_000
      maximum-pool-size: 50
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      register-mbeans: true
  liquibase:
    change-log: classpath:/migrations/changelog-master.xml
  data:
    web:
      pageable:
        one-indexed-parameters: true

  lifecycle:
    timeout-per-shutdown-phase: 1m

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
