apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.database | default .Release.Name | quote }}
