apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ b64enc .Values.username }}
  POSTGRES_PASSWORD: {{ b64enc .Values.password }}

