apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-sender-config
  labels:
    project: shortcut-k8s-application
    app: mail-sender
    env: dev
data:
  SMTP_HOST: 'smtp.gmail.com'
  SMTP_PORT: '587'

  application.properties: |
    spring.kafka.bootstrap-servers=http://kafka:9092
    spring.mail.host=${SMTP_HOST}
    spring.mail.port=${SMTP_PORT}
    spring.mail.username=${SMTP_USER}
    spring.mail.password=${SMTP_PASSWORD}
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
