apiVersion: v1
kind: Secret
metadata:
  name: users-app-secret
  labels:
    project: shortcut-k8s-application
    app: users
    env: dev
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzcw==

