apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-sender.fullname" . }}
  labels:
    {{- include "mail-sender.labels" . | nindent 4 }}
data:
  KAFKA_SERVER: {{ .Values.kafka.server | quote }}
  KAFKA_PORT: {{ .Values.kafka.port | quote }}
  {{- if .Values.smtp.enabled }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  {{- end }}
  REDIS_DATABASE: {{ .Values.redis.database | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}

  application.properties: |
    spring.kafka.bootstrap-servers=${KAFKA_SERVER}:${KAFKA_PORT}
    spring.data.redis.database=${REDIS_DATABASE}
    spring.data.redis.host=${REDIS_HOST}
    spring.data.redis.port=${REDIS_PORT}

    {{- if .Values.smtp.enabled }}
    spring.mail.host=${SMTP_HOST}
    spring.mail.port=${SMTP_PORT}
    spring.mail.username=${SMTP_USER}
    spring.mail.password=${SMTP_PASSWORD}
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
    {{- end }}
