apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-sender.fullname" . }}
  labels:
    {{- include "mail-sender.labels" . | nindent 4 }}
data:
  SMTP_USER: {{ b64enc .Values.smtp.username }}
  SMTP_PASSWORD: {{ b64enc .Values.smtp.password }}

