apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-sender.fullname" . }}
  labels:
    {{- include "mail-sender.labels" . | nindent 4 }}
data:
  {{- if .Values.smtp.enabled }}
  SMTP_USER: {{ b64enc .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ b64enc .Values.smtp.password | quote }}
  {{- end }}
