apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "users-app.fullname" . }}
  labels:
    {{- include "users-app.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  KAFKA_SERVER: {{ .Values.kafka.server | quote }}
  KAFKA_PORT: {{ .Values.kafka.port | quote }}

  application.properties: |
    spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.kafka.bootstrap-servers=http://${KAFKA_SERVER}:${KAFKA_PORT}
