apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "users-app.fullname" . }}
  labels:
    {{- include "users-app.labels" . | nindent 4 }}
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
