apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users-app.fullname" . }}
  labels:
    {{- include "users-app.labels" . | nindent 4 }}
data:
  DB_USERNAME: {{ b64enc .Values.database.username }}
  DB_PASSWORD: {{ b64enc .Values.database.password }}

