apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app-deployment
  labels:
    project: shortcut-k8s-application
    app: users
    env: dev
spec:
  selector:
    matchLabels:
      service: users-app
  template:
    metadata:
      labels:
        service: users-app
    spec:
      containers:
        - name: users
          image: shortcut/users:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
              name: users-app-port
          envFrom:
            - configMapRef:
                name: users-app-config
            - secretRef:
                name: users-app-secret
          args:
            - "--spring.config.import=/opt/apt/config/application.properties"
          resources:
            limits:
              memory: 900M
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /opt/apt/config/application.properties
              subPath: application.properties
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: users-app-config
