apiVersion: v1
kind: Service
metadata:
  name: users-app-service
  labels:
    app: shortcut-k8s-application
    env: dev
spec:
  selector:
    service: users
  ports:
    - name: app-listener
      protocol: TCP
      port: 8080
      targetPort: users-app-port