apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    project: shortcut-k8s-application
    app: zookeeper
    env: dev
spec:
  selector:
    app: zookeeper
  ports:
    - name: zookeeper-listener
      port: 2181
      targetPort: zookeeper-port
