apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db-deployment
  labels:
    app: shortcut-k8s-application
    env: dev
spec:
  selector:
    matchLabels:
      service: users-db
  template:
    metadata:
      labels:
        service: users-db
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: users-db-port
#          envFrom:
#            - configMapRef:
#                name: postgres
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_DB
              value: users_app_db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: users-db-data
      volumes:
        - name: users-db-data
          persistentVolumeClaim:
            claimName: users-db-pvc
