apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-db-statefulset
  labels:
    app: shortcut-k8s-application
    env: dev
spec:
  serviceName: users-db-service
  selector:
    matchLabels:
      service: users-db
  template:
    metadata:
      labels:
        service: users-db
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /pre-stop.sh
          ports:
            - containerPort: 5432
              name: users-db-port
#          envFrom:
#            - configMapRef:
#                name: postgres
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_DB
              value: users_app_db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: users-db-data
  volumeClaimTemplates:
    - metadata:
        name: users-db-data
        labels:
          app: shortcut-k8s-application
          env: dev
      spec:
        volumeName: users-db-pv
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
