apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-db-pv
  labels:
    app: shortcut-k8s-application
    env: dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: E:\tmp\k8s\users\postgres\data
    type: DirectoryOrCreate

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: users-db-pvc
  labels:
    app: shortcut-k8s-application
    env: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
