apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-db-pv
  labels:
    app: shortcut-k8s-application
    env: dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/e/tmp/k8s/users/postgres/data
    type: DirectoryOrCreate
