fullnameOverride: users-app

database:
  host: users-db
  port: 5432
  name: users_app_db
  username: user
  password: pass

kafka:
  server: kafka
  port: 9092

autoscaling:
  enabled: true
  minReplicas: 2
